# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Pg7N5ydrStaX05fdFtOWslpmt8TRaje

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0105EN-SkillsNetwork/labs/Module2/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

#### Add your code below following the instructions given in the course

Exercise 2: Create markdown cell with title of the notebook

Create a markdown cell with the title Data Science Tools and Ecosystem using H1 style heading.
Take a screenshot of the markdown cell and name it as 2-title.png<br> (Images can be saved with either the .jpg or .png extension.)

# Data Science Tools and Ecosystem

Exercise 3 - Create a markdown cell for an introduction

Write an introductory sentence about the notebook such as the follows:

In this notebook, Data Science Tools and Ecosystem are summarized.
Take a screenshot of the markdown cell and name it as 3-intro.png<br> (Images can be saved with either the .jpg or .png extension.)

**_Description:- In this notebook, Data Science Tools and Ecosystem are summarized._**

Exercise 10 - Insert a markdown cell to list Objectives

**Below** the introduction cell created in **Exercise 3**, insert a new markdown cell to list the objectives that this notebook covered (i.e. some of the key takeaways from the course).<br> In this new cell start with an introductory line titled: Objectives: in bold font.<br> Then using an unordered list (bullets) indicate 3 to 5 items covered in this notebook, such as List popular languages for Data Science.<br><br>
Take a screenshot of the markdown cell and name it as 10-objectives.png<br> (Images can be saved with either the .jpg or .png extension.)

**Objectives:**

+ List popular languages for Daata Science
+ List popular libraries used for Data Science
+ List popular tools used for Data Science
+ Learn to use the markdown cell operations
+ Learn to use the code cell operations
+ Learn to evaluate arithmetic expressions

Exercise 4 - Create a markdown cell to list data science languages

Start the cell with an overview line such as:

Some of the popular languages that Data Scientists use are:<br>
Then create an ordered list (i.e. numbered) listing 3 (or more) commonly used languages for data science.<br>
Take a screenshot of the markdown cell and name it as 4-dslanguages.png<br> (Images can be saved with either the .jpg or .png extension.)

**Some of the popular languages that Data Scientists use are:**



1. Python
2. R
3. Julia
4. Scala

Exercise 5 - Create a markdown cell to list data science libraries

Add an overview line to the cell like:

Some of the commonly used libraries used by Data Scientists include:<br>
Below this line add an ordered list listing 3 (or more) commonly used libraries in data science.<br>
Take a screenshot of the markdown cell and name it as 5-dslibraries.png<br> (Images can be saved with either the .jpg or .png extension.)

**Some of the commonly used libraries used by Data Scientists include:**



1. pandas
2. numpy
3. scikit-learn
4. matplotlib
5. seaborn

Exercise 6 - Create a markdown cell with a table of Data Science tools

Create a single column table in this cell with the first row containing the header Data Science Tools. The subsequent three rows in the table should indicate three development environment open source tools used in data science.

Take a screenshot of the markdown cell and name it as 6-dstools.png<br> (Images can be saved with either the .jpg or .png extension.)<br><br>
Hint: Refer to Lab: Using Markdowns in Jupyter Notebooks to create a table.

|Data Science Tools|
--------------------
|Jupyter Notebook|
|R Studio|
|VS Code|
|Spyder|

Exercise 7 - Create a markdown cell introducing arithmetic expression examples

Add a line in this cell with H3 style heading with text like:

Below are a few examples of evaluating arithmetic expressions in Python.<br>
Take a screenshot of the markdown cell and name it as 7-introarithmetic.png<br> (Images can be saved with either the .jpg or .png extension.)

### Below are a few examples of evaluating arithmetic expressions in Python.

Exercise 8 - Create a code cell to multiply and add numbers

In this code cell evaluate the expression (3*4)+5.<br>
Insert a comment line before the expression to explain the operation e.g.<br>  This a simple arithmetic expression to mutiply then add integers.<br>
Then execute the cell to ensure the expression returns the expected output of 17.<br><br>
Take a screenshot of the code cell with output and name it as 8-multiplyandaddintegers.png<br> (Images can be saved with either the .jpg or .png extension.)
"""

# This a simple arithmetic expression to mutiply then add integers.
(3*4)+5

"""Exercise 9 - Create a code cell to convert minutes to hours

In this code cell write an expression that converts 200 minutes into hours.<br>
Insert a comment line before the expression to explain the operation e.g. <br> This will convert 200 minutes to hours by diving by 60.<br>
Run the cell to evaluate the expression.<br><br>
Take a screenshot of the code cell with output and name it as 9-hourstominutes.png<br> (Images can be saved with either the .jpg or .png extension.)
"""

# This will convert 200 minutes to hours by diving by 60.
minute_value = 200
minutes_to_hours = minute_value/60
minutes_to_hours

"""Exercise 11 - Create a markdown cell to indicate the Author's name

In this markdown cell markdown cell include the following text Author in H2 style heading.<br> Include your name as regular text below the word Author.<br><br>
Take a screenshot of the markdown cell and name it as 11-authordetails.png (Images can be saved with either the .jpg or .png extension.)
<br><br>
Note: Save and download the notebook.

## **Author:**

ANAND PESHKARSINGH YADAV
"""

